#!/bin/bash

set -euo pipefail

echo "==== local job info ===="
date
hostname
whoami
nvidia-smi -L

EVOLUTION_ROOT=/home/zjh/Evolution_PC
EVOLUTION_OTHER_ROOT=/home/zjh/Evolution_PC/Isaaclab_other
ISAACLAB_ROOT=/home/zjh/IsaacLab
ISAAC_ENV_PREFIX=/home/zjh/miniconda3/envs/evolution_isaaclab

export TERM=xterm
export PYTHONUNBUFFERED=1
export ACCEPT_EULA=Y
export PRIVACY_CONSENT=Y
export CUDA_VISIBLE_DEVICES=0
export CONDA_PREFIX="$ISAAC_ENV_PREFIX"
export PATH="$ISAAC_ENV_PREFIX/bin:$PATH"
export EVOLUTION_ROOT="$EVOLUTION_ROOT"
export ISAACLAB_ROOT="$ISAACLAB_ROOT"
export ISAAC_SIM_SETUP=/dev/null
export EVOLUTION_LOG_ROOT="$EVOLUTION_ROOT/evolution_tasks/logs"

export ISAACLAB_NUM_ENVS="${ISAACLAB_NUM_ENVS:-4096}"
export EVOLUTION_PPO_HORIZON_LENGTH="${EVOLUTION_PPO_HORIZON_LENGTH:-16}"
export EVOLUTION_PPO_MINIBATCH_SIZE="${EVOLUTION_PPO_MINIBATCH_SIZE:-4096}"
export EVOLUTION_PPO_MINI_EPOCHS="${EVOLUTION_PPO_MINI_EPOCHS:-5}"
export EVOLUTION_PARALLEL_SLOTS="${EVOLUTION_PARALLEL_SLOTS:-1}"
export EVOLUTION_PARALLEL_SPLIT_ENVS="${EVOLUTION_PARALLEL_SPLIT_ENVS:-0}"
export EVOLUTION_STONEGRIND_NUM_ENVS="${EVOLUTION_STONEGRIND_NUM_ENVS:-64}"
export ISAACLAB_MAX_ITERATIONS="${ISAACLAB_MAX_ITERATIONS:-800}"
# Two-stage sparse curriculum: stage two resumes the stage-one policy and
# trains through epoch 800, so each task still receives 800 total epochs.
export EVOLUTION_STAGE1_MAX_ITERATIONS="${EVOLUTION_STAGE1_MAX_ITERATIONS:-200}"
export EVOLUTION_STAGE2_MAX_ITERATIONS="${EVOLUTION_STAGE2_MAX_ITERATIONS:-800}"
export EVOLUTION_STAGE2_TOP_FRACTION="${EVOLUTION_STAGE2_TOP_FRACTION:-1.0}"
export EVOLUTION_TASK_SUCCESS_SCORE=1000
unset EVOLUTION_SINGLE_STAGE_NAME
export EVOLUTION_STANDARD_VARIATION=0.2
export EVOLUTION_STANDARD_LENGTH=0.1
export EVOLUTION_CHECKPOINT_INTERVAL="${EVOLUTION_CHECKPOINT_INTERVAL:-50}"
export EVOLUTION_KEEP_LATEST_CHECKPOINTS=1
export EVOLUTION_KEEP_BEST_CHECKPOINTS=1
export EVOLUTION_REUSE_ISAAC_PROCESS="${EVOLUTION_REUSE_ISAAC_PROCESS:-1}"
# High-env Isaac scene switches can corrupt native memory; isolate every task.
export EVOLUTION_ISAAC_WORKER_MAX_REQUESTS="${EVOLUTION_ISAAC_WORKER_MAX_REQUESTS:-1}"
export EVOLUTION_ISAAC_WORKER_REQUEST_TIMEOUT=14400
export EVOLUTION_ISAAC_WORKER_STALL_TIMEOUT="${EVOLUTION_ISAAC_WORKER_STALL_TIMEOUT:-180}"
export EVOLUTION_EXPERIMENT_NAME="${EVOLUTION_EXPERIMENT_NAME:-exp_20260809_v5b_4tasks_env4096_h16_mb4096_isolated}"
export EVOLUTION_FORCE_NEW_LINEAGE="${EVOLUTION_FORCE_NEW_LINEAGE:-1}"
export EVOLUTION_MAX_GENERATION="${EVOLUTION_MAX_GENERATION:-15}"
export EVOLUTION_MAX_POPULATION="${EVOLUTION_MAX_POPULATION:-16}"
export EVOLUTION_MAX_VARIATION="${EVOLUTION_MAX_VARIATION:-1}"
export EVOLUTION_INITIAL_POPULATION_SIZE="${EVOLUTION_INITIAL_POPULATION_SIZE:-8}"
export EVOLUTION_INITIAL_POPULATION_ATTEMPTS=200
export EVOLUTION_INITIAL_POPULATION_VARIATION=0.05
export EVOLUTION_INITIAL_POPULATION_LENGTH=0.02
export EVOLUTION_TASKS=Isaac-EvolutionHand-Grasp-v0,Isaac-EvolutionHand-BranchGrasp-v0,Isaac-EvolutionHand-Forage-v0,Isaac-EvolutionHand-Strike-v0

export OMP_NUM_THREADS=16
export MKL_NUM_THREADS=16
export NUMEXPR_NUM_THREADS=16
export DISABLE_DEFAULT_GROUND_PLANE=1

mkdir -p "$EVOLUTION_ROOT/evolution_tasks/logs/evolution_task"
mkdir -p "$EVOLUTION_ROOT/parallel_eval_slots"

cd "$EVOLUTION_OTHER_ROOT"
"$ISAAC_ENV_PREFIX/bin/python" main_evolution.py
