#!/bin/bash

set -euo pipefail

EVOLUTION_ROOT=/home/zjh/Evolution_PC
ISAACLAB_ROOT=/home/zjh/IsaacLab
ISAAC_ENV_PREFIX=/home/zjh/miniconda3/envs/evolution_isaaclab

export TERM=xterm PYTHONUNBUFFERED=1 ACCEPT_EULA=Y PRIVACY_CONSENT=Y
export CUDA_VISIBLE_DEVICES=0
export CONDA_PREFIX="$ISAAC_ENV_PREFIX" PATH="$ISAAC_ENV_PREFIX/bin:$PATH"
export EVOLUTION_ROOT ISAACLAB_ROOT ISAAC_SIM_SETUP=/dev/null
export EVOLUTION_LOG_ROOT="$EVOLUTION_ROOT/evolution_tasks/logs"

# One Isaac process is the stable default on a single RTX 4090. The values
# remain externally overridable for an explicit multi-slot experiment.
export ISAACLAB_NUM_ENVS=4096
export EVOLUTION_PARALLEL_SLOTS=1
export EVOLUTION_PARALLEL_SPLIT_ENVS=0
export OMP_NUM_THREADS=8 MKL_NUM_THREADS=8 NUMEXPR_NUM_THREADS=8
export EVOLUTION_PPO_HORIZON_LENGTH=16
export EVOLUTION_PPO_MINIBATCH_SIZE=4096
export EVOLUTION_PPO_MINI_EPOCHS=5
export ISAACLAB_MAX_ITERATIONS="${ISAACLAB_MAX_ITERATIONS:-800}"
export EVOLUTION_STAGE1_MAX_ITERATIONS="${EVOLUTION_STAGE1_MAX_ITERATIONS:-100}"
export EVOLUTION_STAGE2_MAX_ITERATIONS="${EVOLUTION_STAGE2_MAX_ITERATIONS:-250}"
export EVOLUTION_STAGE2_TOP_FRACTION="${EVOLUTION_STAGE2_TOP_FRACTION:-0.25}"

# Preserve the previous formal per-task PPO budgets. Task success and
# physical quality remain separately measured; saturation is not assumed.
export EVOLUTION_TASK_MAX_ITERATIONS_STAGE1="${EVOLUTION_TASK_MAX_ITERATIONS_STAGE1:-Isaac-EvolutionHand-Forage-v0=25,Isaac-EvolutionHand-Strike-v0=25}"
export EVOLUTION_TASK_MAX_ITERATIONS_STAGE2="${EVOLUTION_TASK_MAX_ITERATIONS_STAGE2:-Isaac-EvolutionHand-Forage-v0=50,Isaac-EvolutionHand-Strike-v0=50}"
export EVOLUTION_SCRIPTED_PREFLIGHT=0
export EVOLUTION_REQUIRE_SCRIPTED_PREFLIGHT_SUCCESS=0
export EVOLUTION_SCRIPTED_PREFLIGHT_TIMEOUT=900
export EVOLUTION_INHERIT_POLICY=1
export EVOLUTION_SEED_POLICY_LINEAGE="${EVOLUTION_SEED_POLICY_LINEAGE:-$EVOLUTION_ROOT/Isaaclab_other/exp_20261001_fast15_parallel2_kinadapt_fast_v3.json}"
export EVOLUTION_SEED_POLICY_INDIVIDUAL="${EVOLUTION_SEED_POLICY_INDIVIDUAL:-15_0}"

# Recycle after a bounded number of scene switches.  Unlimited reuse leaks
# native Kit/PhysX state across changing morphologies and can exit mid-task.
export EVOLUTION_REUSE_ISAAC_PROCESS=1
export EVOLUTION_ISAAC_WORKER_MAX_REQUESTS="${EVOLUTION_ISAAC_WORKER_MAX_REQUESTS:-4}"
export EVOLUTION_ISAAC_RESTART_AT_BOUNDARIES="${EVOLUTION_ISAAC_RESTART_AT_BOUNDARIES:-1}"
export EVOLUTION_ISAAC_WORKER_STALL_TIMEOUT=180
export EVOLUTION_ISAAC_SCENE_INIT_LOCK_TIMEOUT=600
export EVOLUTION_ISAAC_WORKER_REQUEST_TIMEOUT=14400
export EVOLUTION_CHECKPOINT_INTERVAL=50
export EVOLUTION_KEEP_LATEST_CHECKPOINTS=1 EVOLUTION_KEEP_BEST_CHECKPOINTS=1

export EVOLUTION_EXPERIMENT_NAME="${EVOLUTION_EXPERIMENT_NAME:-exp_20261008_strikephaseBC15g_v10}"
export EVOLUTION_FORCE_NEW_LINEAGE="${EVOLUTION_FORCE_NEW_LINEAGE:-1}"
export EVOLUTION_MAX_GENERATION="${EVOLUTION_MAX_GENERATION:-15}"
export EVOLUTION_MAX_POPULATION="${EVOLUTION_MAX_POPULATION:-8}"
export EVOLUTION_INITIAL_POPULATION_SIZE="${EVOLUTION_INITIAL_POPULATION_SIZE:-8}"
export EVOLUTION_MAX_VARIATION="${EVOLUTION_MAX_VARIATION:-1}"
# Optional 8 parents + 8 children -> top 8 selection.  Keep disabled for
# legacy runs; enable with MAX_VARIATION=1 for the one-to-two-day schedule.
export EVOLUTION_RETAIN_PARENT_ELITES="${EVOLUTION_RETAIN_PARENT_ELITES:-1}"
export EVOLUTION_INITIAL_POPULATION_ATTEMPTS="${EVOLUTION_INITIAL_POPULATION_ATTEMPTS:-200}"
export EVOLUTION_INITIAL_POPULATION_VARIATION="${EVOLUTION_INITIAL_POPULATION_VARIATION:-0.05}"
export EVOLUTION_INITIAL_POPULATION_LENGTH="${EVOLUTION_INITIAL_POPULATION_LENGTH:-0.02}"
export EVOLUTION_TASKS="${EVOLUTION_TASKS:-Isaac-EvolutionHand-Grasp-v0,Isaac-EvolutionHand-BranchGrasp-v0,Isaac-EvolutionHand-Forage-v0,Isaac-EvolutionHand-Strike-v0}"
export DISABLE_DEFAULT_GROUND_PLANE=1

# User-authorized formal run: Forage quality is monitoring/final acceptance.
export EVOLUTION_BC_SEED_MORPHOLOGY_LINEAGE="$EVOLUTION_ROOT/Isaaclab_other/exp_20261005_branchgrasp_BC15g_v9.json"
export EVOLUTION_BC_SEED_MORPHOLOGY_INDIVIDUAL=13_14
export EVOLUTION_BC_PRESERVE_SEED_CHILD=1
export EVOLUTION_VERIFIED_SEED_BC_MANIFEST="$EVOLUTION_ROOT/Isaaclab_other/verified_seed_bc_13_14.json"
export EVOLUTION_SEED_POLICY_LINEAGE="$EVOLUTION_ROOT/Isaaclab_other/exp_20261005_branchgrasp_BC15g_v9.json"
export EVOLUTION_SEED_POLICY_INDIVIDUAL=13_14
export EVOLUTION_BRANCH_BC_MODE=1 EVOLUTION_STRIKE_BC_MODE=1
export EVOLUTION_STRIKE_RESET_THUMB_SPREAD=-2.0
export EVOLUTION_STRIKE_PREGRASP_ACTION=0.55
export EVOLUTION_STRIKE_RESET_OFFSET_WORLD=0,0,0
export EVOLUTION_STRIKE_BC_TEACHER_DEFAULT_CHECKPOINT="$EVOLUTION_ROOT/evolution_tasks/logs/evolution_task/strike_bc_stage2_13_14_10diverse_seed17_bcinit/nn/bc_init.pth"
export EVOLUTION_BC_EPOCHS=10 EVOLUTION_STRIKE_BC_EPOCHS=0
export EVOLUTION_ISAAC_TASK_THREADS=1

mkdir -p "$EVOLUTION_LOG_ROOT/evolution_task" "$EVOLUTION_ROOT/parallel_eval_slots"
cd "$EVOLUTION_ROOT/Isaaclab_other"
exec "$ISAAC_ENV_PREFIX/bin/python" main_evolution.py
