#!/bin/bash

set -euo pipefail

echo "==== local job info ===="
date
hostname
whoami
nvidia-smi -L

EVOLUTION_ROOT=/home/zjh/Evolution_PC
EVOLUTION_OTHER_ROOT=/home/zjh/Evolution_PC/Isaaclab_other
ISAACLAB_ROOT=/home/zjh/IsaacLab
ISAAC_ENV_PREFIX=/home/zjh/miniconda3/envs/evolution_isaaclab

export TERM=xterm
export PYTHONUNBUFFERED=1
export ACCEPT_EULA=Y
export PRIVACY_CONSENT=Y
export CUDA_VISIBLE_DEVICES=0
export CONDA_PREFIX="$ISAAC_ENV_PREFIX"
export PATH="$ISAAC_ENV_PREFIX/bin:$PATH"
export EVOLUTION_ROOT="$EVOLUTION_ROOT"
export ISAACLAB_ROOT="$ISAACLAB_ROOT"
export ISAAC_SIM_SETUP=/dev/null
export EVOLUTION_LOG_ROOT="$EVOLUTION_ROOT/evolution_tasks/logs"

export ISAACLAB_NUM_ENVS=128
export EVOLUTION_PARALLEL_SLOTS=2
export EVOLUTION_PARALLEL_SPLIT_ENVS=0
export EVOLUTION_STONEGRIND_NUM_ENVS=64
export ISAACLAB_MAX_ITERATIONS=200
export EVOLUTION_STAGE1_MAX_ITERATIONS=200
export EVOLUTION_STAGE2_MAX_ITERATIONS=500
export EVOLUTION_STAGE2_TOP_FRACTION=0.2
export EVOLUTION_STANDARD_VARIATION=0.2
export EVOLUTION_STANDARD_LENGTH=0.1
export EVOLUTION_CHECKPOINT_INTERVAL=50
export EVOLUTION_KEEP_LATEST_CHECKPOINTS=1
export EVOLUTION_KEEP_BEST_CHECKPOINTS=1
export EVOLUTION_EXPERIMENT_NAME=exp_20260722_evolutionpc_grasponly_hold10_25g
export EVOLUTION_FORCE_NEW_LINEAGE=0
export EVOLUTION_MAX_GENERATION=25
export EVOLUTION_MAX_POPULATION=16
export EVOLUTION_MAX_VARIATION=3
export EVOLUTION_INITIAL_POPULATION_SIZE=8
export EVOLUTION_INITIAL_POPULATION_ATTEMPTS=200
export EVOLUTION_INITIAL_POPULATION_VARIATION=0.05
export EVOLUTION_INITIAL_POPULATION_LENGTH=0.02
export EVOLUTION_TASKS=Isaac-EvolutionHand-Grasp-v0

export OMP_NUM_THREADS=12
export MKL_NUM_THREADS=12
export NUMEXPR_NUM_THREADS=12
export DISABLE_DEFAULT_GROUND_PLANE=1

mkdir -p "$EVOLUTION_ROOT/evolution_tasks/logs/evolution_task"
mkdir -p "$EVOLUTION_ROOT/parallel_eval_slots"

cd "$EVOLUTION_OTHER_ROOT"
"$ISAAC_ENV_PREFIX/bin/python" main_evolution.py
