#!/bin/bash
set -euo pipefail

EVOLUTION_ROOT=/home/zjh/Evolution_PC
ISAAC_ENV_PREFIX=/home/zjh/miniconda3/envs/evolution_isaaclab
export TERM=xterm PYTHONUNBUFFERED=1 ACCEPT_EULA=Y PRIVACY_CONSENT=Y
export CUDA_VISIBLE_DEVICES=0 CONDA_PREFIX="$ISAAC_ENV_PREFIX" PATH="$ISAAC_ENV_PREFIX/bin:$PATH"
export EVOLUTION_ROOT ISAACLAB_ROOT=/home/zjh/IsaacLab ISAAC_SIM_SETUP=/dev/null
export EVOLUTION_LOG_ROOT="$EVOLUTION_ROOT/evolution_tasks/logs"
export ISAACLAB_NUM_ENVS=128 EVOLUTION_PARALLEL_SLOTS=2 EVOLUTION_PARALLEL_SPLIT_ENVS=1 EVOLUTION_REUSE_ISAAC_PROCESS=0
export ISAACLAB_MAX_ITERATIONS=600 EVOLUTION_STAGE1_MAX_ITERATIONS=200 EVOLUTION_STAGE2_MAX_ITERATIONS=600 EVOLUTION_STAGE2_TOP_FRACTION=0.50
export EVOLUTION_EXPERIMENT_NAME=exp_20260804_v3palm_balanced_4tasks_15g_p16_parallel2
export EVOLUTION_FORCE_NEW_LINEAGE=1 EVOLUTION_MAX_GENERATION=15 EVOLUTION_MAX_POPULATION=16 EVOLUTION_MAX_VARIATION=2
export EVOLUTION_INITIAL_POPULATION_SIZE=8 EVOLUTION_INITIAL_POPULATION_ATTEMPTS=200 EVOLUTION_INITIAL_POPULATION_VARIATION=0.05 EVOLUTION_INITIAL_POPULATION_LENGTH=0.02
export EVOLUTION_CHECKPOINT_INTERVAL=50 EVOLUTION_KEEP_LATEST_CHECKPOINTS=1 EVOLUTION_KEEP_BEST_CHECKPOINTS=1
export EVOLUTION_TASKS=Isaac-EvolutionHand-Grasp-v0,Isaac-EvolutionHand-BranchGrasp-v0,Isaac-EvolutionHand-Forage-v0,Isaac-EvolutionHand-Strike-v0
export EVOLUTION_TASK_SCORE_SCALES='{"Isaac-EvolutionHand-BranchGrasp-v0":1000,"Isaac-EvolutionHand-Forage-v0":1000,"Isaac-EvolutionHand-Grasp-v0":2000,"Isaac-EvolutionHand-Strike-v0":1000}'
export OMP_NUM_THREADS=12 MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 DISABLE_DEFAULT_GROUND_PLANE=1
mkdir -p "$EVOLUTION_ROOT/evolution_tasks/logs/evolution_task" "$EVOLUTION_ROOT/parallel_eval_slots"
cd "$EVOLUTION_ROOT/Isaaclab_other"
exec "$ISAAC_ENV_PREFIX/bin/python" main_evolution.py
