#!/bin/bash
set -euo pipefail

EVOLUTION_ROOT=/home/zjh/Evolution_PC
EVOLUTION_OTHER_ROOT="$EVOLUTION_ROOT/Isaaclab_other"
ISAACLAB_ROOT=/home/zjh/IsaacLab
ISAAC_ENV_PREFIX=/home/zjh/miniconda3/envs/evolution_isaaclab

export TERM=xterm PYTHONUNBUFFERED=1 ACCEPT_EULA=Y PRIVACY_CONSENT=Y
export CUDA_VISIBLE_DEVICES=0 CONDA_PREFIX="$ISAAC_ENV_PREFIX" PATH="$ISAAC_ENV_PREFIX/bin:$PATH"
export EVOLUTION_ROOT ISAACLAB_ROOT ISAAC_SIM_SETUP=/dev/null
export EVOLUTION_LOG_ROOT="$EVOLUTION_ROOT/evolution_tasks/logs"
export ISAACLAB_NUM_ENVS=128 EVOLUTION_PARALLEL_SLOTS=1 EVOLUTION_REUSE_ISAAC_PROCESS=0
export ISAACLAB_MAX_ITERATIONS=300 EVOLUTION_STAGE1_MAX_ITERATIONS=100
export EVOLUTION_STAGE2_MAX_ITERATIONS=300 EVOLUTION_STAGE2_TOP_FRACTION=0.25
export EVOLUTION_EXPERIMENT_NAME=exp_20260723_feasibility_5tasks_25g_p16
export EVOLUTION_FORCE_NEW_LINEAGE=1 EVOLUTION_MAX_GENERATION=25 EVOLUTION_MAX_POPULATION=16
export EVOLUTION_MAX_VARIATION=2 EVOLUTION_INITIAL_POPULATION_SIZE=8
export EVOLUTION_INITIAL_POPULATION_ATTEMPTS=200 EVOLUTION_INITIAL_POPULATION_VARIATION=0.05
export EVOLUTION_INITIAL_POPULATION_LENGTH=0.02
export EVOLUTION_CHECKPOINT_INTERVAL=50 EVOLUTION_KEEP_LATEST_CHECKPOINTS=1 EVOLUTION_KEEP_BEST_CHECKPOINTS=1
export EVOLUTION_TASKS=Isaac-EvolutionHand-Grasp-v0,Isaac-EvolutionHand-BranchGrasp-v0,Isaac-EvolutionHand-Carry-v0,Isaac-EvolutionHand-Forage-v0,Isaac-EvolutionHand-Strike-v0
export OMP_NUM_THREADS=12 MKL_NUM_THREADS=12 NUMEXPR_NUM_THREADS=12 DISABLE_DEFAULT_GROUND_PLANE=1

mkdir -p "$EVOLUTION_ROOT/evolution_tasks/logs/evolution_task" "$EVOLUTION_ROOT/parallel_eval_slots"
cd "$EVOLUTION_OTHER_ROOT"
exec "$ISAAC_ENV_PREFIX/bin/python" main_evolution.py
